# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ac171da0e515b4a858286fba38060761627aa3238ad87cfcba25aec5f592fb4504b5d3738ac11ccb8e45c687e845abe68f162086d29ff0f1b360567f63b0007

test:
  secret_key_base: c155f9516b60d051e6ee24f03d0cd7bcfeeeaa7a0a07a6fce6ae0d71e8fb338b9e39d1730f2e859ca70d5a12e990597087c8257171dc1d8be7524c85fc76cb01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
